const { callQwenAPI } = require('../config/qwen');
const { createSchemaSummary } = require('./schemaService');
const { getActiveDatabase, getDatabaseById } = require('./databaseManager');
const { getPDFContent } = require('./pdfService');
const { executeQuery } = require('./chatService');
const { formatDataForWidget } = require('./dashboardInsightService');

// Auto-generate a complete dashboard using AI
async function autoGenerateDashboard(databaseId = null) {
  try {
    // Get active database if not provided
    let activeDb;
    if (!databaseId) {
      const { getActiveDatabase } = require('./databaseManager');
      activeDb = await getActiveDatabase();
      if (!activeDb) {
        throw new Error('No database selected. Please select a database in Settings.');
      }
      databaseId = activeDb.id;
    } else {
      activeDb = await getDatabaseById(databaseId);
    }

    // Get database type and instructions
    const dbType = activeDb?.database_type?.toLowerCase() || 'postgresql';
    const dbInstructions = activeDb?.instructions || '';

    // Get schema summary
    const schemaSummary = createSchemaSummary(databaseId);
    const schemaJson = JSON.stringify(schemaSummary.slice(0, 150), null, 2); // Limit to 150 tables

    // Get PDF context for business understanding
    const pdfContext = getPDFContent(8000);

    // Database-specific SQL instructions
    let dbTypeInstructions = '';
    if (dbType === 'mysql') {
      dbTypeInstructions = `
**CRITICAL MySQL Syntax Rules:**
- Use LIKE (not ILIKE) for case-insensitive pattern matching. For case-insensitive search, use: LOWER(column) LIKE LOWER('%pattern%')
- Use backticks (\`) for table and column names if they contain special characters
- Use LIMIT for result limiting (e.g., LIMIT 100)
- Use DATE_FORMAT(), YEAR(), MONTH(), DAY() for date functions
- Use CONCAT() for string concatenation (not ||)
`;
    } else {
      dbTypeInstructions = `
**CRITICAL PostgreSQL Syntax Rules:**
- Use ILIKE (not LIKE) for case-insensitive pattern matching (e.g., column ILIKE '%pattern%')
- Use double quotes (") for identifiers if needed
- Use LIMIT ... OFFSET for pagination
- Use || for string concatenation
- Use TO_CHAR(), DATE_TRUNC(), EXTRACT() for date functions
- Use window functions where appropriate
`;
    }

    const prompt = `You are an AI assistant that creates comprehensive business dashboards by analyzing database schemas.

Database Type: ${dbType.toUpperCase()}
Database Schema (${schemaSummary.length} tables available):
${schemaJson}

${pdfContext ? `\nApplication Context (AMAST Sales Manual - DMS):\n${pdfContext}\n` : ''}

${dbTypeInstructions}

${dbInstructions ? `**Database-Specific Instructions:**\n${dbInstructions}\n` : ''}

Your task is to analyze this database schema and generate a comprehensive set of dashboard insights (8-12 widgets) that would be valuable for business users.

For each insight, you should:
1. Identify meaningful business metrics (revenue, sales, inventory, customers, etc.)
2. Choose appropriate visualization types (kpi, line_chart, bar_chart, pie_chart, table)
3. Generate correct ${dbType.toUpperCase()}-compatible SQL queries
4. Provide clear, business-friendly titles and descriptions

Widget Types Available:
- kpi: Single number/metric (e.g., total revenue, count of items)
- line_chart: Time series data (e.g., sales over time)
- bar_chart: Categorical comparison (e.g., sales by outlet, top products)
- pie_chart: Distribution/breakdown (e.g., sales by category, revenue by region)
- table: Detailed data listing

Return a JSON array with 8-12 dashboard items. Each item should have:
{
  "title": "Business-friendly title (e.g., 'Total Revenue This Month')",
  "description": "What this insight shows",
  "widget_type": "kpi|line_chart|bar_chart|pie_chart|table",
  "sql_query": "SELECT query here (${dbType.toUpperCase()} syntax)",
  "position": 1 (increment for each item)
}

Important Rules:
- Use ONLY column names that exist in the schema
- Generate ${dbType.toUpperCase()}-compatible SQL syntax
- Always include LIMIT for large result sets (max 1000 rows)
- SELECT only (no INSERT, UPDATE, DELETE, DROP, ALTER)
- For KPIs: Return a single row with a single numeric value
- For charts: Return rows with name/value pairs (first column = name/label, second = value)
- For tables: Return all relevant columns
- Focus on business value: revenue, sales trends, top performers, inventory status, customer metrics
- Include a mix of widget types for variety
- Make titles clear and descriptive

Return ONLY a valid JSON array, no other text. Format:
[
  {
    "title": "...",
    "description": "...",
    "widget_type": "...",
    "sql_query": "...",
    "position": 1
  },
  ...
]`;

    const messages = [
      { role: 'system', content: 'You are an expert at creating business dashboards. Return only valid JSON arrays.' },
      { role: 'user', content: prompt },
    ];

    console.log('🤖 Generating dashboard insights with AI...');
    const response = await callQwenAPI(messages, 0.7);
    
    // Extract JSON from response
    let jsonText = response.trim();
    if (jsonText.includes('```json')) {
      jsonText = jsonText.split('```json')[1].split('```')[0].trim();
    } else if (jsonText.includes('```')) {
      jsonText = jsonText.split('```')[1].split('```')[0].trim();
    }

    const insights = JSON.parse(jsonText);
    
    if (!Array.isArray(insights) || insights.length === 0) {
      throw new Error('AI did not return valid insights array');
    }

    console.log(`✅ Generated ${insights.length} dashboard insights`);

    // Validate and execute each query to ensure they work
    const validatedInsights = [];
    for (let i = 0; i < insights.length; i++) {
      const insight = insights[i];
      try {
        // Test the query
        const queryResults = await executeQuery(insight.sql_query, [], null, null, databaseId);
        
        // Format the data
        const formattedData = formatDataForWidget(insight.widget_type, {
          data: queryResults.rows,
          columns: queryResults.columns,
        });

        validatedInsights.push({
          ...insight,
          widget_config: formattedData,
          validated: true,
        });
      } catch (error) {
        console.warn(`⚠️  Skipping insight "${insight.title}": ${error.message}`);
        // Skip invalid queries but continue with others
      }
    }

    if (validatedInsights.length === 0) {
      throw new Error('No valid insights could be generated. Please check your database schema.');
    }

    console.log(`✅ Validated ${validatedInsights.length} insights`);

    return validatedInsights;

  } catch (error) {
    console.error('Error auto-generating dashboard:', error);
    throw error;
  }
}

module.exports = {
  autoGenerateDashboard,
};



