const express = require('express');
const { authenticateToken, requireAdmin } = require('../middleware/auth');
const { query } = require('../config/database');
const { generateInsight, executeInsightQuery, formatDataForWidget } = require('../services/dashboardInsightService');
const { getQueryBuilderSchema, buildSQLFromSelections } = require('../services/queryBuilderService');
const { autoGenerateDashboard } = require('../services/autoDashboardService');
const { getActiveDatabase } = require('../services/databaseManager');
const logger = require('../services/loggerService');

const router = express.Router();

// All routes require authentication
router.use(authenticateToken);

// Get all dashboard items (view-only for all users)
router.get('/', async (req, res) => {
  try {
    const activeDb = await getActiveDatabase();
    if (!activeDb) {
      return res.json({ items: [] });
    }

    const result = await query(
      `SELECT 
        id, title, description, widget_type, widget_config, 
        position, width, height, is_active,
        created_by, created_at, updated_at
       FROM chat_app_dashboard_items
       WHERE is_active = true AND database_id = $1 AND database_id IS NOT NULL
       ORDER BY position ASC, created_at ASC`,
      [activeDb.id]
    );
    
    // Parse widget_config if it's a string (PostgreSQL JSONB is already parsed, but ensure consistency)
    const items = result.rows.map(item => ({
      ...item,
      widget_config: typeof item.widget_config === 'string' 
        ? JSON.parse(item.widget_config) 
        : item.widget_config,
    }));
    
    res.json({ items });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: 'Failed to fetch dashboard items' });
  }
});

// Get single dashboard item
router.get('/:id', async (req, res) => {
  try {
    const itemId = parseInt(req.params.id);
    const result = await query(
      'SELECT * FROM chat_app_dashboard_items WHERE id = $1',
      [itemId]
    );
    
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Dashboard item not found' });
    }
    
    // Parse widget_config if it's a string
    const item = result.rows[0];
    item.widget_config = typeof item.widget_config === 'string' 
      ? JSON.parse(item.widget_config) 
      : item.widget_config;
    
    res.json({ item });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: 'Failed to fetch dashboard item' });
  }
});

// Create dashboard item (admin only)
router.post('/', requireAdmin, async (req, res) => {
  try {
    const { title, description, widget_type, widget_config, sql_query, position, width, height } = req.body;
    
    if (!title || !widget_type || !widget_config) {
      return res.status(400).json({ error: 'Missing required fields: title, widget_type, widget_config' });
    }

    const activeDb = await getActiveDatabase();
    if (!activeDb) {
      return res.status(400).json({ error: 'No database selected. Please select a database in Settings.' });
    }

    // Get max position for this database
    const positionResult = await query(
      'SELECT COALESCE(MAX(position), 0) as max_pos FROM chat_app_dashboard_items WHERE database_id = $1',
      [activeDb.id]
    );
    const nextPosition = position || (positionResult.rows[0].max_pos + 1);

    const result = await query(
      `INSERT INTO chat_app_dashboard_items 
       (database_id, title, description, widget_type, widget_config, sql_query, position, width, height, created_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
       RETURNING *`,
      [activeDb.id, title, description || null, widget_type, JSON.stringify(widget_config), sql_query || null, nextPosition, width || 4, height || 3, req.user.userId]
    );

    // Parse widget_config if it's a string
    const item = result.rows[0];
    item.widget_config = typeof item.widget_config === 'string' 
      ? JSON.parse(item.widget_config) 
      : item.widget_config;

    logger.logChatActivity('Dashboard item created', req.user.userId, null, { itemId: item.id, title, databaseId: activeDb.id });
    res.json({ item });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to create dashboard item' });
  }
});

// Update dashboard item (admin only)
router.put('/:id', requireAdmin, async (req, res) => {
  try {
    const itemId = parseInt(req.params.id);
    const { title, description, widget_type, widget_config, sql_query, position, width, height, is_active } = req.body;

    const updates = [];
    const values = [];
    let paramIndex = 1;

    if (title !== undefined) {
      updates.push(`title = $${paramIndex++}`);
      values.push(title);
    }
    if (description !== undefined) {
      updates.push(`description = $${paramIndex++}`);
      values.push(description);
    }
    if (widget_type !== undefined) {
      updates.push(`widget_type = $${paramIndex++}`);
      values.push(widget_type);
    }
    if (widget_config !== undefined) {
      updates.push(`widget_config = $${paramIndex++}`);
      values.push(JSON.stringify(widget_config));
    }
    if (sql_query !== undefined) {
      updates.push(`sql_query = $${paramIndex++}`);
      values.push(sql_query);
    }
    if (position !== undefined) {
      updates.push(`position = $${paramIndex++}`);
      values.push(position);
    }
    if (width !== undefined) {
      updates.push(`width = $${paramIndex++}`);
      values.push(width);
    }
    if (height !== undefined) {
      updates.push(`height = $${paramIndex++}`);
      values.push(height);
    }
    if (is_active !== undefined) {
      updates.push(`is_active = $${paramIndex++}`);
      values.push(is_active);
    }

    updates.push(`updated_at = CURRENT_TIMESTAMP`);
    values.push(itemId);

    const result = await query(
      `UPDATE chat_app_dashboard_items 
       SET ${updates.join(', ')}
       WHERE id = $${paramIndex}
       RETURNING *`,
      values
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Dashboard item not found' });
    }

    // Parse widget_config if it's a string
    const item = result.rows[0];
    item.widget_config = typeof item.widget_config === 'string' 
      ? JSON.parse(item.widget_config) 
      : item.widget_config;

    logger.logChatActivity('Dashboard item updated', req.user.userId, null, { itemId, title: item.title });
    res.json({ item });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to update dashboard item' });
  }
});

// Delete dashboard item (admin only)
router.delete('/:id', requireAdmin, async (req, res) => {
  try {
    const itemId = parseInt(req.params.id);
    
    const result = await query(
      'DELETE FROM chat_app_dashboard_items WHERE id = $1 RETURNING id',
      [itemId]
    );

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Dashboard item not found' });
    }

    logger.logChatActivity('Dashboard item deleted', req.user.userId, null, { itemId });
    res.json({ success: true, message: 'Dashboard item deleted successfully' });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to delete dashboard item' });
  }
});

// AI: Generate insight from natural language (admin only)
router.post('/generate-insight', requireAdmin, async (req, res) => {
  try {
    const { request, conversationHistory = [] } = req.body;
    
    if (!request) {
      return res.status(400).json({ error: 'Request is required' });
    }

    const activeDb = await getActiveDatabase();
    if (!activeDb) {
      return res.status(400).json({ error: 'No database selected. Please select a database in Settings.' });
    }

    const result = await generateInsight(request, conversationHistory, activeDb.id);
    
    res.json(result);
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to generate insight' });
  }
});

// Execute insight query and get formatted data (admin only for preview)
router.post('/preview-insight', requireAdmin, async (req, res) => {
  try {
    const { sql_query, widget_type } = req.body;
    
    if (!sql_query || !widget_type) {
      return res.status(400).json({ error: 'sql_query and widget_type are required' });
    }

    const activeDb = await getActiveDatabase();
    if (!activeDb) {
      return res.status(400).json({ error: 'No database selected' });
    }

    const queryResult = await executeInsightQuery(sql_query, activeDb.id);
    
    if (!queryResult.success) {
      return res.status(400).json({ error: queryResult.error });
    }

    const formattedData = formatDataForWidget(widget_type, queryResult);
    
    res.json({
      success: true,
      data: formattedData,
      rawData: queryResult.data,
      columns: queryResult.columns,
      rowCount: queryResult.rowCount,
    });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to preview insight' });
  }
});

// Get schema for query builder (admin only)
router.get('/query-builder/schema', requireAdmin, async (req, res) => {
  try {
    const activeDb = await getActiveDatabase();
    if (!activeDb) {
      return res.status(400).json({ error: 'No database selected. Please select a database in Settings.' });
    }

    const schema = getQueryBuilderSchema(activeDb.id);
    if (!schema) {
      return res.status(404).json({ error: 'Schema not found. Please extract schema first.' });
    }

    res.json({ schema });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to get query builder schema' });
  }
});

// Build SQL from query builder selections (admin only)
router.post('/query-builder/build-sql', requireAdmin, async (req, res) => {
  try {
    const { selections } = req.body;
    
    if (!selections) {
      return res.status(400).json({ error: 'Selections are required' });
    }

    const activeDb = await getActiveDatabase();
    if (!activeDb) {
      return res.status(400).json({ error: 'No database selected' });
    }

    const sql = await buildSQLFromSelections(selections, activeDb.id);
    
    res.json({ 
      success: true, 
      sql,
      widgetType: selections.widgetType || 'table',
    });
  } catch (error) {
    logger.logError(error, req);
    res.status(400).json({ error: error.message || 'Failed to build SQL' });
  }
});

// Get data for a dashboard item (all users can view)
router.get('/:id/data', async (req, res) => {
  try {
    const itemId = parseInt(req.params.id);
    
    const activeDb = await getActiveDatabase();
    if (!activeDb) {
      return res.status(400).json({ error: 'No database selected' });
    }

    const itemResult = await query(
      'SELECT sql_query, widget_type, widget_config, database_id FROM chat_app_dashboard_items WHERE id = $1 AND is_active = true',
      [itemId]
    );

    if (itemResult.rows.length === 0) {
      return res.status(404).json({ error: 'Dashboard item not found' });
    }

    const item = itemResult.rows[0];
    
    // Ensure the item belongs to the active database
    if (!item.database_id || item.database_id !== activeDb.id) {
      return res.status(403).json({ error: 'Dashboard item does not belong to the selected database' });
    }
    
    if (!item.sql_query) {
      return res.json({ success: true, data: null, message: 'No query configured' });
    }

    const queryResult = await executeInsightQuery(item.sql_query, activeDb.id);
    
    if (!queryResult.success) {
      return res.status(400).json({ error: queryResult.error });
    }

    const formattedData = formatDataForWidget(item.widget_type, queryResult);
    
    res.json({
      success: true,
      data: formattedData,
      rawData: queryResult.data,
      columns: queryResult.columns,
      rowCount: queryResult.rowCount,
    });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to fetch dashboard item data' });
  }
});

// Auto-generate complete dashboard (admin only)
router.post('/auto-generate', requireAdmin, async (req, res) => {
  try {
    const activeDb = await getActiveDatabase();
    if (!activeDb) {
      return res.status(400).json({ error: 'No database selected. Please select a database in Settings.' });
    }

    logger.logChatActivity('Auto-generating dashboard', req.user.userId, null, { databaseId: activeDb.id });

    // Generate insights using AI
    const insights = await autoGenerateDashboard(activeDb.id);

    // Get max position for this database
    const positionResult = await query(
      'SELECT COALESCE(MAX(position), 0) as max_pos FROM chat_app_dashboard_items WHERE database_id = $1',
      [activeDb.id]
    );
    let nextPosition = positionResult.rows[0].max_pos + 1;

    // Save all insights to database
    const savedItems = [];
    for (const insight of insights) {
      try {
        const result = await query(
          `INSERT INTO chat_app_dashboard_items 
           (database_id, title, description, widget_type, widget_config, sql_query, position, width, height, created_by)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
           RETURNING id, title, widget_type, position`,
          [
            activeDb.id,
            insight.title,
            insight.description || null,
            insight.widget_type,
            JSON.stringify(insight.widget_config),
            insight.sql_query,
            insight.position || nextPosition++,
            4, // Default width
            3, // Default height
            req.user.userId
          ]
        );
        savedItems.push(result.rows[0]);
      } catch (error) {
        console.error(`Error saving insight "${insight.title}":`, error);
        // Continue with other insights
      }
    }

    logger.logChatActivity('Dashboard auto-generated', req.user.userId, null, { 
      databaseId: activeDb.id,
      itemsCreated: savedItems.length 
    });

    res.json({
      success: true,
      message: `Successfully generated ${savedItems.length} dashboard insights`,
      items: savedItems,
      totalGenerated: insights.length,
      totalSaved: savedItems.length,
    });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to auto-generate dashboard' });
  }
});

// Cleanup route: Deactivate old dashboard items with NULL database_id (admin only)
router.post('/cleanup-old-items', requireAdmin, async (req, res) => {
  try {
    const result = await query(
      `UPDATE chat_app_dashboard_items 
       SET is_active = false 
       WHERE database_id IS NULL AND is_active = true
       RETURNING id, title`
    );
    
    logger.logChatActivity('Cleaned up old dashboard items', req.user.userId, null, { 
      itemsDeactivated: result.rows.length 
    });
    
    res.json({
      success: true,
      message: `Deactivated ${result.rows.length} old dashboard items with no database association`,
      items: result.rows
    });
  } catch (error) {
    logger.logError(error, req);
    res.status(500).json({ error: error.message || 'Failed to cleanup old items' });
  }
});

module.exports = router;

